name: HideMyArmors
version: '${version}'
main: top.mrxiaom.hidemyarmors.HideMyArmors
api-version: 1.13
depend: [ ProtocolLib ]
authors: [ MrXiaoM ]
folia-supported: true
commands:
  hidemyarmors:
    description: 管理装备隐藏设置
    usage: |
      /hidemyarmors hide <slot|all> - 隐藏指定槽位
      /hidemyarmors show <slot|all> - 显示指定槽位
      /hidemyarmors status - 查看当前隐藏状态
      /hidemyarmors reload - 重载配置文件 (仅OP)
      可用槽位:
        head - 头盔
        chest - 胸甲
        legs - 护腿
        feet - 靴子
        all - 所有装备
      别名: /hma
    aliases: [hma]
